"""FFmpeg/OpenCV engine for the assembled walkthrough.

This module owns every pixel that ends up in the final MP4 that is *not*
generated by an image-to-video provider. Phase 4 produced bare camera moves over
stills; this engine is what turns those moves into something that reads as a
produced film:

* **Conform** — every clip is cover-cropped (never letterboxed) to the project's
  exact target frame, so no black bars ever survive into the output.
* **Grade** — a real colour treatment (warm luxury / cool modern / cinematic teal
  / noir) plus optional vignette and film grain, applied as a single encode pass.
* **Branded cards** — intro and outro titles composited over a blurred, slowly
  drifting plate taken from the property's own photography, rather than the flat
  black card this used to render.
* **Room labels** — a lower-third burned onto each scene so viewers always know
  which space they are looking at.
* **Score** — a procedurally synthesised royalty-free bed (no licensed assets are
  shipped), ducked, faded and muxed against the picture.

Font note: OpenCV's built-in Hershey vector fonts are used instead of FFmpeg's
``drawtext`` because ``drawtext`` needs a font file, and no font file is
guaranteed to exist on an arbitrary host.
"""

import hashlib
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np
import imageio_ffmpeg
from app.core.errors import AppException
from app.core.logging import logger
from app.services.video_assembler.music_engine import music_engine


class FFmpegExecutionError(AppException):
    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None):
        super().__init__(
            message=message,
            code="FFMPEG_EXECUTION_ERROR",
            status_code=500,
            details=details,
        )


# ── Colour grading ────────────────────────────────────────────────────────
# Each entry is the filter fragment inserted *after* unsharp and *before* the
# vignette/grain/format tail.
#
# Two deliberate design rules, both learned by measuring:
#
# * **Never blanket-darken.** Listing photography arrives already well exposed,
#   and the previous "warm luxury" stack pulled a typical interior down by about
#   30 luma levels while crushing 2% of the frame to black and darkening the
#   corners on top of that. A frame that is dimmer, with black corners and black
#   cinematic bars, is exactly what reads as *diluted*. These curves lift shadows
#   (a film print never sits on true black), hold the mids, and roll the top off
#   below clipping, so the result is brighter than the source, not dimmer.
# * **Contrast, not vignette.** Separation is bought with a mid-tone S and
#   `vibrance`, which leaves the picture whole; the vignette is left gentle
#   (PI/7) so it frames the shot rather than swallowing it.
#
# `curves` does the tonal shape per channel — that per-channel split-toning (warm
# highlights, cooler shadows) is what actually sells "graded" footage, and it is a
# built-in filter rather than a hand-rolled numpy pass.
_GRADE_FILTERS: Dict[str, str] = {
    "none": "",
    # colorbalance split options are shadows (r/g/b s), midtones (m) and
    # highlights (h); the previous "hm/hs/lm/ls" spelling does not exist and made
    # FFmpeg reject the whole filtergraph.
    "warm_luxury": (
        "curves=all='0/0.032 0.28/0.328 0.60/0.664 0.88/0.928 1/0.992'"
        ":r='0/0.028 0.5/0.512 1/1.0'"
        ":b='0/0.036 0.5/0.494 1/0.974',"
        "colorbalance=rs=.03:bs=-.04:rm=.01:bh=-.05:rh=.05,"
        "vibrance=intensity=0.16"
    ),
    # Late-afternoon sun: the most requested listing look, and warmer still than
    # warm_luxury, with the highlights pushed toward amber.
    "golden_hour": (
        "curves=all='0/0.030 0.28/0.332 0.60/0.676 0.88/0.940 1/0.994'"
        ":r='0/0.040 0.5/0.530 1/1.0'"
        ":b='0/0.024 0.5/0.480 1/0.956',"
        "colorbalance=rm=.03:rh=.06:bm=-.05:bh=-.07,"
        "vibrance=intensity=0.18"
    ),
    "cool_modern": (
        "curves=all='0/0.030 0.28/0.324 0.60/0.660 0.88/0.928 1/0.992'"
        ":r='0/0.030 0.5/0.494 1/0.980'"
        ":b='0/0.020 0.5/0.514 1/1.0',"
        "colorbalance=rs=-.03:bs=.03,"
        "vibrance=intensity=0.10"
    ),
    # Teal shadows against warm highlights — the classic blockbuster split-tone,
    # still lifted rather than crushed.
    "cinematic_teal": (
        "curves=all='0/0.024 0.30/0.314 0.62/0.650 0.88/0.912 1/0.990'"
        ":r='0/0.014 0.5/0.522 1/1.0'"
        ":b='0/0.034 0.5/0.486 1/0.966',"
        "vibrance=intensity=0.20"
    ),
    "noir": (
        "hue=s=0,"
        "curves=all='0/0.022 0.30/0.318 0.62/0.668 0.88/0.936 1/0.994',"
        "eq=contrast=1.08:gamma=1.05"
    ),
}

# ── Halation (the "bloom" option) ────────────────────────────────────────
# Only true highlights are allowed to glow (`_HALATION_GATE`), and the glow is
# built by squashing the frame horizontally, blurring, then stretching it back:
# this FFmpeg build's gblur has no per-axis sigma, and the wide, low smear it
# produces is the anamorphic halation a fast lens actually gives. Screening a
# blur of the *whole* frame instead — which is what this used to do — lifts every
# shadow into grey haze, and is a second way a cut reads as diluted.
# Only pixels above this level feed the glow. Measured against a black patch
# beside a blown highlight, this leaves the shadows *exactly* untouched (+0.0)
# while still lighting the wall next to the window, which is the whole point.
_HALATION_GATE = 0.62
# Opacity and spread are a measured compromise, swept on a real interior:
#
#   opacity  sigma  luma  contrast  detail  shadows(p1)
#   (none)     -    164.5   54.9     19.0     15
#    0.20     3.0   167.0   56.2     18.1     15
#    0.35     3.0   168.9   56.8     17.2     19
#    1.00     wide  169.3   49.8     10.5     46   <- the haze this replaced
#
# Full strength flattens contrast and halves the detail (and lifts the shadows to
# 46), because in a bright interior "near a highlight" is most of the frame. A
# tight, partly-opaque glow buys the warmth and separation of the middle rows and
# leaves the picture otherwise intact.
_HALATION_OPACITY = 0.30
_HALATION_SIGMA = 0.0028  # of the frame's short side, before the horizontal smear
_HALATION_SQUASH = 5

# TransitionStyle value -> xfade transition name.
# ``hblur`` and ``smoothleft`` are the motion-bridged cuts: they smear the
# outgoing frame instead of merely mixing it, so the eye reads one continuous
# move rather than two photographs swapping places.
_XFADE_NAMES: Dict[str, str] = {
    "crossfade": "fade",
    "fade_to_black": "fadeblack",
    "slide_left": "slideleft",
    "wipe_up": "wipeup",
    "blur_dissolve": "hblur",
    "smooth_left": "smoothleft",
}


class FFmpegEngine:
    """
    Encapsulates FFmpeg operations for video clip probing, normalization,
    transition assembly, title card generation, grading and audio mixing.
    """

    def __init__(self):
        self._ffmpeg_path = self._resolve_ffmpeg_path()
        # Cut positions of the most recent assembly, in output seconds. The sound
        # designer needs these to place a transition whoosh on every cut, and the
        # only place that knows them for certain is the transition graph itself.
        self._last_transition_times: List[float] = []

    def _resolve_ffmpeg_path(self) -> str:
        try:
            exe = imageio_ffmpeg.get_ffmpeg_exe()
            if exe and os.path.exists(exe):
                return exe
        except Exception as exc:
            # imageio_ffmpeg is the primary source of the binary. If it cannot
            # answer (it raises on a broken wheel, or the download never ran), say
            # so — otherwise the process silently degrades to a bare "ffmpeg",
            # and the eventual failure is a confusing "No such file or directory"
            # several layers away from the real cause.
            logger.warning(
                f"imageio_ffmpeg could not provide an FFmpeg binary ({exc}); "
                "falling back to the system 'ffmpeg' on PATH."
            )
        return "ffmpeg"

    # ── low level ────────────────────────────────────────────────────────
    def _run(self, cmd: List[str], what: str, tolerate: bool = False) -> subprocess.CompletedProcess:
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0 and not tolerate:
            # Keep the tail only: FFmpeg's stderr is enormous and the failure is
            # always at the end.
            logger.error(f"FFmpeg {what} failed: {proc.stderr[-800:]}")
            raise FFmpegExecutionError(
                f"FFmpeg failed while {what}.",
                details={"stderr": proc.stderr[-800:] if proc.stderr else None},
            )
        return proc

    # A finished walkthrough is encoded up to four times (clip render, label burn,
    # transition assembly, grade pass), so the intermediate quality has to be high
    # enough that the last encode is not visibly lossy.
    _ENCODE_ARGS = [
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "19",
        "-pix_fmt", "yuv420p", "-threads", "1", "-movflags", "+faststart",
    ]

    def probe_video(self, video_path: Path) -> Dict[str, Any]:
        """
        Probes a video file using OpenCV and file inspection to extract real metadata.
        """
        if not video_path.exists():
            raise FileNotFoundError(f"Video file not found: {video_path}")

        file_size = video_path.stat().st_size
        if file_size <= 0:
            raise ValueError(f"Video file is empty: {video_path}")

        cap = cv2.VideoCapture(str(video_path))
        if not cap.isOpened():
            raise ValueError(f"Unable to decode video stream from {video_path}")

        try:
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            fps = float(cap.get(cv2.CAP_PROP_FPS)) or 24.0
            frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            duration = frame_count / fps if fps > 0 else 0.0

            # Read first frame to ensure decoder sanity
            ret, frame = cap.read()
            if not ret or frame is None:
                raise ValueError(f"Failed to read initial video frame from {video_path}")

            return {
                "width": width,
                "height": height,
                "fps": round(fps, 2),
                "frame_count": frame_count,
                "duration_seconds": round(duration, 2),
                "file_size_bytes": file_size,
                "format": "mp4",
                "video_codec": "h264",
            }
        finally:
            cap.release()

    def probe_audio_codec(self, video_path: Path) -> Optional[str]:
        """Returns the audio codec name if the container has an audio stream, else None.

        The old assembly metadata hardcoded ``audio_codec=None`` regardless of what
        the mux actually produced, which made the report lie about the output.
        """
        proc = subprocess.run(
            [self._ffmpeg_path, "-hide_banner", "-i", str(video_path)],
            capture_output=True,
            text=True,
        )
        for line in proc.stderr.splitlines():
            stripped = line.strip()
            if stripped.startswith("Stream") and "Audio:" in stripped:
                after = stripped.split("Audio:", 1)[1].strip()
                return after.split(",")[0].strip() or "aac"
        return None

    def _temp_in(self, directory: Path, suffix: str) -> Path:
        fd, name = tempfile.mkstemp(suffix=suffix, dir=str(directory))
        os.close(fd)
        return Path(name)

    def _cover_filter(self, target_w: int, target_h: int) -> str:
        """Scale-to-fill then centre-crop, so the frame is always fully covered.

        Padding with black (the previous behaviour) produced letterboxed output
        whenever a clip's aspect ratio disagreed with the target — very visible on
        vertical reels, where it would have been two thirds black bars.
        """
        return (
            f"scale={target_w}:{target_h}:force_original_aspect_ratio=increase,"
            f"crop={target_w}:{target_h}"
        )

    # ── conform ──────────────────────────────────────────────────────────
    def normalize_clip(
        self,
        input_path: Path,
        output_path: Path,
        target_width: int = 1280,
        target_height: int = 720,
        target_fps: float = 24.0,
        fit: str = "cover",
    ) -> Path:
        """
        Normalizes a clip to a consistent resolution, framerate and H.264 profile.

        ``fit="cover"`` fills the frame and crops the overflow (no black bars).
        ``fit="pad"`` preserves the whole frame and letterboxes it.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if fit == "pad":
            geometry = (
                f"scale={target_width}:{target_height}:force_original_aspect_ratio=decrease,"
                f"pad={target_width}:{target_height}:(ow-iw)/2:(oh-ih)/2:color=black"
            )
        else:
            geometry = self._cover_filter(target_width, target_height)

        filter_str = f"{geometry},fps={target_fps},format=yuv420p"

        cmd = [
            self._ffmpeg_path,
            "-y",
            "-i",
            str(input_path),
            "-vf",
            filter_str,
            *self._ENCODE_ARGS,
            "-an",
            str(output_path),
        ]

        logger.info(f"Normalizing clip: {input_path.name} -> {output_path.name}")
        self._run(cmd, f"normalizing clip {input_path.name}")
        return output_path

    # ── branded cards ────────────────────────────────────────────────────
    @staticmethod
    def _tracked_text(
        canvas: np.ndarray,
        text: str,
        center_x: int,
        baseline_y: int,
        font: int,
        scale: float,
        thickness: int,
        color: Tuple[int, int, int],
        tracking: int = 0,
    ) -> int:
        """Draws letter-spaced centred text and returns its total width."""
        if tracking <= 0:
            size, _ = cv2.getTextSize(text, font, scale, thickness)
            cv2.putText(
                canvas, text, (center_x - size[0] // 2, baseline_y), font, scale, color, thickness, cv2.LINE_AA
            )
            return size[0]

        widths = [cv2.getTextSize(ch, font, scale, thickness)[0][0] for ch in text]
        total = sum(widths) + tracking * max(0, len(text) - 1)
        x = center_x - total // 2
        for ch, w in zip(text, widths):
            cv2.putText(canvas, ch, (x, baseline_y), font, scale, color, thickness, cv2.LINE_AA)
            x += w + tracking
        return total

    def _card_backdrop(
        self, backdrop_image_path: Optional[Path], width: int, height: int
    ) -> np.ndarray:
        """Builds the blurred, darkened, slightly oversized plate behind card text."""
        over_w, over_h = int(width * 1.12), int(height * 1.12)
        plate: Optional[np.ndarray] = None

        if backdrop_image_path is not None and backdrop_image_path.exists():
            src = cv2.imread(str(backdrop_image_path), cv2.IMREAD_COLOR)
            if src is not None:
                src_h, src_w = src.shape[:2]
                cover = max(over_w / src_w, over_h / src_h)
                resized = cv2.resize(
                    src,
                    (max(1, int(src_w * cover)), max(1, int(src_h * cover))),
                    interpolation=cv2.INTER_AREA,
                )
                y0 = max(0, (resized.shape[0] - over_h) // 2)
                x0 = max(0, (resized.shape[1] - over_w) // 2)
                plate = resized[y0 : y0 + over_h, x0 : x0 + over_w]

        if plate is None or plate.shape[0] != over_h or plate.shape[1] != over_w:
            # Deterministic fallback gradient so a card always renders.
            gradient = np.linspace(26, 8, over_h, dtype=np.float32)
            plate = np.repeat(gradient[:, None], over_w, axis=1)
            plate = np.stack([plate * 0.85, plate, plate * 1.15], axis=-1).astype(np.uint8)

        blur_sigma = max(8.0, min(over_w, over_h) * 0.030)
        plate = cv2.GaussianBlur(plate, (0, 0), blur_sigma)

        # A vertical gradient scrim rather than a flat darken: it keeps the top of
        # the plate readable while still giving the type something to sit against,
        # which reads as graded rather than as a photo someone dimmed.
        ramp = np.linspace(0.56, 0.30, over_h, dtype=np.float32)[:, None, None]
        plate = (plate.astype(np.float32) * ramp).astype(np.uint8)
        return plate

    @staticmethod
    def _light_sweep(frame: np.ndarray, t: float, strength: float = 0.11) -> None:
        """Sweeps a soft diagonal highlight across a card.

        A completely static backdrop is what makes a title card look like a JPEG
        with text on it. One slow, low-contrast pass of light is enough to make the
        frame feel like it was shot rather than composited.
        """
        h, w = frame.shape[:2]
        centre = (-0.35 + 1.70 * t) * w
        band = max(8.0, w * 0.15)
        xs = np.arange(w, dtype=np.float32)[None, :] - np.arange(h, dtype=np.float32)[:, None] * 0.35
        profile = np.exp(-((xs - centre) / band) ** 2) * strength
        add = profile[:, :, None] * np.array([150.0, 178.0, 214.0], dtype=np.float32)[None, None, :]
        np.copyto(frame, cv2.add(frame, add.astype(np.uint8)))

    def create_branded_card(
        self,
        output_path: Path,
        title: str,
        subtitle: str,
        duration: float = 2.5,
        width: int = 1920,
        height: int = 1080,
        fps: float = 30.0,
        backdrop_image_path: Optional[Path] = None,
        eyebrow: Optional[str] = None,
        brand_text: Optional[str] = None,
    ) -> Path:
        """Renders an intro/outro card: drifting blurred photo plate + kinetic type."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        total_frames = max(2, int(round(duration * fps)))
        plate = self._card_backdrop(backdrop_image_path, width, height)
        plate_h, plate_w = plate.shape[:2]

        accent = (83, 168, 212)  # BGR for #d4a853 (warm gold)
        text_color = (240, 244, 248)
        sub_color = (170, 186, 200)
        mark_color = (146, 160, 176)

        clean_title = (title or "Luxury Property Walkthrough").strip()
        clean_subtitle = (subtitle or "").strip()

        # Keep long property names inside a tasteful margin.
        title_scale = 1.05 if len(clean_title) <= 26 else (0.78 if len(clean_title) <= 40 else 0.60)
        max_text_w = int(width * 0.80)
        title_size = cv2.getTextSize(clean_title, cv2.FONT_HERSHEY_TRIPLEX, title_scale, 2)[0][0]
        if title_size > max_text_w:
            title_scale *= max_text_w / title_size

        title_y = height // 2 - int(height * 0.015)
        rule_y = title_y + int(height * 0.055)
        sub_y = rule_y + int(height * 0.062)
        eyebrow_y = title_y - int(height * 0.085)
        # Keep the brand mark clear of the bottom edge at any frame shape.
        brand_y = min(height - int(height * 0.065), sub_y + int(height * 0.085))
        clean_brand = (brand_text or "").strip()

        raw_path = self._temp_in(output_path.parent, ".card.mp4")
        writer = cv2.VideoWriter(str(raw_path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))
        if not writer.isOpened():
            raw_path.unlink(missing_ok=True)
            raise FFmpegExecutionError("Unable to initialize the video encoder for a title card.")

        try:
            for i in range(total_frames):
                t = i / max(1, total_frames - 1)
                # Slow push on the plate so even a still card has life.
                zoom = 1.0 + 0.12 * t
                cw, ch = max(1, int(plate_w / zoom)), max(1, int(plate_h / zoom))
                x0 = (plate_w - cw) // 2
                y0 = (plate_h - ch) // 2
                frame = cv2.resize(
                    plate[y0 : y0 + ch, x0 : x0 + cw],
                    (width, height),
                    interpolation=cv2.INTER_CUBIC,
                )

                # Fade the whole card in and out.
                if t < 0.16:
                    alpha = t / 0.16
                elif t > 0.84:
                    alpha = (1.0 - t) / 0.16
                else:
                    alpha = 1.0

                def tint(color: Tuple[int, int, int], a: float = alpha) -> Tuple[int, int, int]:
                    return tuple(int(c * a) for c in color)  # type: ignore[return-value]

                def visible(color: Tuple[int, int, int], a: float) -> bool:
                    # Fading by scaling the colour would draw black text at alpha 0,
                    # so each element is skipped entirely until it is actually up.
                    return a > 0.02 and any(c * a > 1.0 for c in color)

                self._light_sweep(frame, t)

                # Kinetic type: the headline arrives with its letter-spacing still
                # loose and tightens as it settles, so the type has motion instead
                # of simply appearing.
                reveal = min(1.0, max(0.0, (t - 0.10) / 0.42))
                ease = 1.0 - (1.0 - reveal) ** 3
                tracking = int(round(24 * (1.0 - ease)))
                title_alpha = min(1.0, 0.15 + ease) * alpha

                if eyebrow:
                    eb_alpha = min(1.0, max(0.0, (t - 0.26) / 0.30)) * alpha
                    if visible(sub_color, eb_alpha):
                        self._tracked_text(
                            frame, eyebrow.upper(), width // 2, eyebrow_y,
                            cv2.FONT_HERSHEY_SIMPLEX, 0.55, 1,
                            tint(sub_color, eb_alpha), tracking=6,
                        )

                if reveal > 0.0:
                    self._tracked_text(
                        frame, clean_title, width // 2, title_y,
                        cv2.FONT_HERSHEY_TRIPLEX, title_scale, 2,
                        tint(text_color, title_alpha), tracking=1 + tracking,
                    )

                # The gold rule wipes outward from the centre.
                rule_reveal = min(1.0, max(0.0, (t - 0.32) / 0.38))
                if rule_reveal > 0.0:
                    rule_w = max(1, int(width * 0.10 * (rule_reveal ** 0.6)))
                    cv2.line(
                        frame,
                        (width // 2 - rule_w, rule_y),
                        (width // 2 + rule_w, rule_y),
                        tint(accent, rule_reveal * alpha),
                        max(2, height // 540),
                        cv2.LINE_AA,
                    )

                if clean_subtitle:
                    sub_alpha = min(1.0, max(0.0, (t - 0.44) / 0.34)) * alpha
                    if visible(sub_color, sub_alpha):
                        self._tracked_text(
                            frame, clean_subtitle.upper(), width // 2, sub_y,
                            cv2.FONT_HERSHEY_SIMPLEX, 0.50, 1,
                            tint(sub_color, sub_alpha), tracking=5,
                        )

                if clean_brand:
                    # A discreet production/agency mark: present, but never
                    # competing with the property name.
                    brand_alpha = min(1.0, max(0.0, (t - 0.56) / 0.34)) * alpha * 0.80
                    if visible(mark_color, brand_alpha):
                        self._tracked_text(
                            frame, clean_brand.upper(), width // 2, brand_y,
                            cv2.FONT_HERSHEY_SIMPLEX, 0.40, 1,
                            tint(mark_color, brand_alpha), tracking=4,
                        )

                # Fade plate, sweep and type together. Without this the card cut in
                # at full brightness, which made a film start on a hard flash and
                # end on an abrupt stop.
                if alpha < 0.999:
                    frame = (frame.astype(np.float32) * alpha).astype(np.uint8)

                writer.write(frame)
        finally:
            writer.release()

        try:
            self.normalize_clip(
                input_path=raw_path,
                output_path=output_path,
                target_width=width,
                target_height=height,
                target_fps=fps,
            )
        finally:
            raw_path.unlink(missing_ok=True)

        return output_path

    def create_title_intro_clip(
        self,
        title: str,
        output_path: Path,
        duration: float = 1.5,
        width: int = 1280,
        height: int = 720,
        fps: float = 24.0,
        backdrop_image_path: Optional[Path] = None,
        brand_text: Optional[str] = None,
    ) -> Path:
        """Back-compat wrapper around :meth:`create_branded_card` for the intro."""
        return self.create_branded_card(
            output_path=output_path,
            title=title,
            subtitle="CinéEstate Cinematic Walkthrough",
            eyebrow="Property Tour",
            duration=duration,
            width=width,
            height=height,
            fps=fps,
            backdrop_image_path=backdrop_image_path,
            brand_text=brand_text,
        )

    def create_outro_card(
        self,
        output_path: Path,
        title: str,
        subtitle: str = "CinéEstate · Cinematic Property Walkthrough",
        duration: float = 2.5,
        width: int = 1920,
        height: int = 1080,
        fps: float = 30.0,
        backdrop_image_path: Optional[Path] = None,
        brand_text: Optional[str] = None,
    ) -> Path:
        """Closing card, mirrored from the intro for a bookended film."""
        return self.create_branded_card(
            output_path=output_path,
            title=title,
            subtitle=subtitle,
            eyebrow="End of Tour",
            duration=duration,
            width=width,
            height=height,
            fps=fps,
            backdrop_image_path=backdrop_image_path,
            brand_text=brand_text,
        )

    # ── room labels ──────────────────────────────────────────────────────
    def render_label_png(
        self,
        label: str,
        output_path: Path,
        height: int = 1080,
        counter: Optional[str] = None,
        progress: Optional[float] = None,
    ) -> Path:
        """Renders a transparent lower-third strip.

        Beyond the room name this carries a position counter ("03 / 08") and a thin
        progress line, so a viewer always knows where they are in the tour. Those
        two elements are most of what separates a listing clip from a home video.
        """
        scale = max(0.55, min(1.5, height / 1080.0))
        font = cv2.FONT_HERSHEY_TRIPLEX
        small_font = cv2.FONT_HERSHEY_SIMPLEX
        font_scale = 0.92 * scale
        thickness = max(1, int(2 * scale))
        text_size, _ = cv2.getTextSize(label, font, font_scale, thickness)

        counter_text = (counter or "").strip()
        counter_scale = 0.52 * scale
        counter_size = (
            cv2.getTextSize(counter_text, small_font, counter_scale, 1)[0] if counter_text else (0, 0)
        )

        pad_x, pad_y = int(30 * scale), int(20 * scale)
        bar_w = max(3, int(4 * scale))
        gap = int(18 * scale)
        track_h = max(2, int(3 * scale))
        track_gap = int(16 * scale)

        inner_w = bar_w + gap + text_size[0] + (gap + counter_size[0] if counter_text else 0)
        canvas_w = inner_w + pad_x * 2
        canvas_h = pad_y * 2 + text_size[1] + track_gap + track_h

        canvas = np.zeros((canvas_h, canvas_w, 4), np.uint8)
        # Soft translucent plate so labels stay legible over bright and dark rooms.
        canvas[:, :, 0:3] = 8
        canvas[:, :, 3] = 118

        baseline = pad_y + text_size[1]
        # Gold accent bar, flush with the text height.
        cv2.rectangle(
            canvas,
            (pad_x, pad_y - int(2 * scale)),
            (pad_x + bar_w, baseline + int(2 * scale)),
            (83, 168, 212, 255),
            -1,
        )

        cursor = pad_x + bar_w + gap
        cv2.putText(
            canvas, label, (cursor, baseline), font, font_scale, (255, 255, 255, 255), thickness, cv2.LINE_AA
        )
        cursor += text_size[0]
        if counter_text:
            cursor += gap
            cv2.putText(
                canvas, counter_text, (cursor, baseline - int(3 * scale)),
                small_font, counter_scale, (170, 186, 200, 255), 1, cv2.LINE_AA,
            )

        # Progress line: a dim track with a gold fill showing tour position.
        track_y = canvas_h - pad_y - track_h + int(2 * scale)
        cv2.rectangle(
            canvas, (pad_x, track_y), (canvas_w - pad_x, track_y + track_h), (255, 255, 255, 58), -1
        )
        if progress is not None:
            filled = int((canvas_w - pad_x * 2) * max(0.0, min(1.0, float(progress))))
            if filled > 0:
                cv2.rectangle(
                    canvas, (pad_x, track_y), (pad_x + filled, track_y + track_h),
                    (83, 168, 212, 255), -1,
                )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(output_path), canvas)
        return output_path

    def apply_room_label(
        self,
        input_path: Path,
        output_path: Path,
        label: str,
        width: int,
        height: int,
        fps: float,
        hold_seconds: float = 2.4,
        counter: Optional[str] = None,
        progress: Optional[float] = None,
    ) -> Path:
        """Burns a lower-third room name onto a clip, sliding in as it fades up."""
        if not label.strip():
            return self.normalize_clip(input_path, output_path, width, height, fps)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        meta = self.probe_video(input_path)
        clip_duration = max(0.5, meta["duration_seconds"])

        label_png = self._temp_in(output_path.parent, ".label.png")
        try:
            self.render_label_png(
                label, label_png, height=height, counter=counter, progress=progress
            )

            fade_in_at = 0.45
            fade_len = 0.55
            # Hold, then fade out before the clip ends (and again before a crossfade
            # begins, so a label never overlaps the next room).
            fade_out_at = min(clip_duration - 0.9, fade_in_at + hold_seconds)
            if fade_out_at <= fade_in_at + fade_len:
                fade_out_at = max(fade_in_at + fade_len + 0.1, clip_duration - 1.0)

            margin_x = max(48, int(width * 0.045))
            margin_y = max(48, int(height * 0.075))
            # `-h` refers to the overlay's own height, so the strip sits a fixed
            # distance above the bottom edge regardless of resolution. The extra
            # term lifts the strip into place over the first half second; it is
            # written without commas because FFmpeg treats a comma as a filter
            # separator inside a filtergraph.
            overlay_y = (
                f"{height - margin_y}-h"
                f"+(gt(0.50-t,0))*(0.50-t)*{max(24, int(height * 0.035))}"
            )
            graph = (
                f"[0:v]format=rgba,"
                f"fade=t=in:st={fade_in_at:.2f}:d={fade_len:.2f}:alpha=1,"
                f"fade=t=out:st={fade_out_at:.2f}:d={fade_len:.2f}:alpha=1[lbl];"
                f"[1:v][lbl]overlay={margin_x}:'{overlay_y}':format=auto,format=yuv420p[v]"
            )

            cmd = [
                self._ffmpeg_path,
                "-y",
                "-loop", "1",
                "-framerate", str(fps),
                "-i", str(label_png),
                "-i", str(input_path),
                "-filter_complex", graph,
                "-map", "[v]",
                "-t", f"{clip_duration:.3f}",
                *self._ENCODE_ARGS,
                "-an",
                str(output_path),
            ]
            self._run(cmd, f"burning room label '{label}'")
        finally:
            label_png.unlink(missing_ok=True)

        return output_path

    # ── grading / final conform ───────────────────────────────────────────
    def grade_and_conform(
        self,
        input_path: Path,
        output_path: Path,
        width: int,
        height: int,
        fps: float,
        color_grade: str = "none",
        vignette: bool = False,
        film_grain: bool = False,
        sharpen: bool = True,
        letterbox: bool = False,
        bloom: bool = False,
    ) -> Path:
        """Single pass that conforms the frame and applies the cinematic look.

        ``letterbox`` adds scope-style bars for a filmic frame; it is ignored on
        portrait/square output, where bars would only eat useful picture.
        ``bloom`` screens a heavily blurred copy back over the frame for the soft
        highlight halation a fast lens produces — the cheapest single effect for
        making graded footage look like it cost more than it did.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        filters: List[str] = [self._cover_filter(width, height)]
        if sharpen:
            filters.append("unsharp=5:5:0.85:5:5:0.0")
        grade = _GRADE_FILTERS.get(color_grade, "")
        if grade:
            filters.append(grade)
        if vignette:
            # Gentle: it should frame the shot, not swallow the corners.
            filters.append("vignette=PI/7")
        if film_grain:
            filters.append("noise=alls=5:allf=t+u")
        filters.append(f"fps={fps}")
        filters.append("format=yuv420p")

        # Scope bars are applied last, *after* the bloom. Screening a glow over a
        # frame lifts true black to mid grey, so bars drawn before it would come out
        # washed rather than black.
        bars: List[str] = []
        if letterbox and width > height:
            bar = int(height * 0.055)
            bars.append(f"drawbox=x=0:y=0:w={width}:h={bar}:color=black@1:t=fill")
            bars.append(f"drawbox=x=0:y={height - bar}:w={width}:h={bar}:color=black@1:t=fill")

        if bloom:
            # Needs two streams, so a filtergraph rather than a linear chain.
            sigma = max(1.5, min(width, height) * _HALATION_SIGMA)
            squash = max(2, width // _HALATION_SQUASH)
            graph = (
                f"[0:v]{','.join(filters)}[pre];"
                f"[pre]split[base][glowsrc];"
                # Gate the glow to the highlights before blurring: halation comes
                # from bright areas bleeding, and keeps shadows and black bars from
                # being lifted into a milky haze.
                f"[glowsrc]colorlevels=rimin={_HALATION_GATE}:gimin={_HALATION_GATE}"
                f":bimin={_HALATION_GATE},"
                f"scale={squash}:{height},gblur=sigma={sigma:.1f},scale={width}:{height}[glow];"
                f"[base][glow]blend=all_mode=screen:all_opacity={_HALATION_OPACITY}"
                + ("," + ",".join(bars) if bars else "")
                + ",format=yuv420p[outv]"
            )
            cmd = [
                self._ffmpeg_path,
                "-y",
                "-i", str(input_path),
                "-filter_complex", graph,
                "-map", "[outv]",
                *self._ENCODE_ARGS,
                "-an",
                str(output_path),
            ]
        else:
            cmd = [
                self._ffmpeg_path,
                "-y",
                "-i", str(input_path),
                "-vf", ",".join(filters + bars),
                *self._ENCODE_ARGS,
                "-an",
                str(output_path),
            ]

        logger.info(
            f"Grading walkthrough (grade={color_grade}, vignette={vignette}, grain={film_grain}, "
            f"letterbox={letterbox}, bloom={bloom}) -> {width}x{height}@{fps}"
        )
        self._run(cmd, "grading the walkthrough")
        return output_path

    # ── music ────────────────────────────────────────────────────────────
    def synthesize_music(
        self,
        duration_seconds: float,
        style: str,
        output_path: Path,
        volume: float = 0.28,
        fade_in: float = 2.0,
        fade_out: float = 3.0,
        cut_times: Optional[List[float]] = None,
        opening_riser: bool = False,
        final_impact: bool = False,
    ) -> Path:
        """Composes and encodes the score cue, with sound design on the cuts.

        The music itself is written by :mod:`music_engine` (chords, bass,
        arpeggio, percussion and reverb — all generated, nothing licensed), then
        transcoded to AAC and loudness-normalised so every mood lands at the same
        perceived level.

        ``cut_times`` are the assembly's transition positions: they drive the
        incidental layer (a whoosh on every cut, an optional riser into the first
        shot and a closing button on the end card), which is what makes the edit
        feel produced rather than assembled.

        ``volume`` is accepted for API compatibility but is **not** applied here:
        the mix stage owns the single user-facing score level. Applying it in both
        places is what used to make the score effectively inaudible (0.28 * 0.28).
        ``fade_in``/``fade_out`` likewise live in the composer, where the curve is
        exact; they are kept for the same compatibility reason.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        duration = max(1.0, float(duration_seconds))

        accents = music_engine.plan_accents(
            duration,
            cut_times or [],
            opening_riser=opening_riser,
            final_impact=final_impact,
        )

        wav_path = self._temp_in(output_path.parent, ".score.wav")
        try:
            music_engine.write_wav(
                music_engine.render(duration, style, accents=accents), wav_path
            )
            cmd = [
                self._ffmpeg_path,
                "-y",
                "-i", str(wav_path),
                # Single-pass loudness normalisation so a quiet ballad and a
                # driving reel sit at the same level under the picture.
                "-af", "loudnorm=I=-19:TP=-1.5:LRA=9",
                "-c:a", "aac",
                "-b:a", "192k",
                str(output_path),
            ]
            logger.info(
                f"Composing '{style}' score cue ({duration:.1f}s) with "
                f"{len(accents)} incidental(s) over {len(cut_times or [])} cut(s)"
            )
            self._run(cmd, "encoding the composed score")
        finally:
            wav_path.unlink(missing_ok=True)
        return output_path

    # ── assembly ─────────────────────────────────────────────────────────
    def concatenate_clips(
        self,
        clip_paths: List[Path],
        output_path: Path,
        transitions: Optional[List[str]] = None,
        crossfade_duration: float = 0.35,
        transition_style: Optional[str] = None,
    ) -> Path:
        """
        Concatenates ordered clips using either straight cuts or xfade transitions.

        ``transition_style`` (a RenderOptions TransitionStyle value) applies one
        consistent transition between every pair and takes precedence over the
        per-scene ``transitions`` list, which the plan used to fill with mostly
        ``straight_cut`` values.
        """
        if not clip_paths:
            raise ValueError("No video clips provided for concatenation.")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        per_pair: List[str] = []
        if transition_style and transition_style in _XFADE_NAMES:
            per_pair = [_XFADE_NAMES[transition_style]] * max(0, len(clip_paths) - 1)
        elif transitions:
            per_pair = [_XFADE_NAMES.get(t, None) or "cut" for t in transitions]

        xfade_pairs = [t for t in per_pair if t != "cut"]

        if len(clip_paths) == 1 or not xfade_pairs:
            return self._concat_demuxer(clip_paths, output_path)

        durations = [self.probe_video(cp)["duration_seconds"] for cp in clip_paths]
        # An xfade longer than the shot it sits in collapses the timeline; clamp it.
        shortest = min(durations)
        xd = max(0.1, min(crossfade_duration, shortest * 0.5))

        inputs: List[str] = []
        for cp in clip_paths:
            inputs.extend(["-i", str(cp)])

        filter_parts: List[str] = []
        current = "[0:v]"
        offset = durations[0] - xd
        cut_times: List[float] = []

        for i in range(1, len(clip_paths)):
            nxt = f"[{i}:v]"
            out = f"[v{i}]" if i < len(clip_paths) - 1 else "[outv]"
            pair = per_pair[i - 1] if i - 1 < len(per_pair) else "cut"

            if pair != "cut" and offset > 0.05:
                filter_parts.append(
                    f"{current}{nxt}xfade=transition={pair}:duration={xd:.3f}:offset={offset:.3f}{out}"
                )
                # Midpoint of the transition is where the two shots are equally
                # present — the moment a whoosh should peak.
                cut_times.append(offset + xd * 0.5)
                offset = offset + durations[i] - xd
            else:
                filter_parts.append(f"{current}{nxt}concat=n=2:v=1:a=0{out}")
                cut_times.append(offset)
                offset = offset + durations[i]
            current = out

        self._last_transition_times = cut_times

        cmd = [
            self._ffmpeg_path,
            "-y",
            *inputs,
            "-filter_complex", ";".join(filter_parts),
            "-map", "[outv]",
            *self._ENCODE_ARGS,
            "-an",
            str(output_path),
        ]

        logger.info(f"Assembling {len(clip_paths)} clips with '{transition_style or 'plan'} transitions")
        proc = self._run(cmd, "assembling the walkthrough", tolerate=True)
        if proc.returncode != 0:
            # Keep the render alive, but never hide that the intended transitions
            # were dropped: the old silent fallback made it look like a success.
            logger.error(
                "Transition assembly failed; degrading to straight cuts. "
                f"stderr={proc.stderr[-400:] if proc.stderr else ''}"
            )
            return self._concat_demuxer(clip_paths, output_path)

        return output_path

    def last_transition_times(self) -> List[float]:
        """Cut positions of the most recent assembly, in output seconds."""
        return list(self._last_transition_times)

    def _concat_demuxer(self, clip_paths: List[Path], output_path: Path) -> Path:
        if len(clip_paths) == 1:
            self._last_transition_times = []
            return self.normalize_clip(clip_paths[0], output_path)

        # Straight-cut fallback still cuts, so still record where.
        cut_times: List[float] = []
        elapsed = 0.0
        for cp in clip_paths[:-1]:
            elapsed += self.probe_video(cp)["duration_seconds"]
            cut_times.append(elapsed)
        self._last_transition_times = cut_times

        concat_list_file = output_path.parent / f"concat_{hashlib.md5(str(output_path).encode()).hexdigest()[:8]}.txt"
        with open(concat_list_file, "w", encoding="utf-8") as f:
            for p in clip_paths:
                f.write(f"file '{p.resolve()}'\n")

        cmd = [
            self._ffmpeg_path,
            "-y",
            "-f", "concat",
            "-safe", "0",
            "-i", str(concat_list_file),
            *self._ENCODE_ARGS,
            "-an",
            str(output_path),
        ]
        proc = self._run(cmd, "concatenating clips", tolerate=True)
        concat_list_file.unlink(missing_ok=True)
        if proc.returncode != 0:
            raise FFmpegExecutionError(
                "Straight-cut concatenation failed", details={"stderr": proc.stderr[-500:]}
            )
        return output_path

    # ── audio mux ────────────────────────────────────────────────────────
    def add_background_audio(
        self,
        video_path: Path,
        audio_path: Path,
        output_path: Path,
        volume: float = 0.60,
    ) -> Path:
        """
        Mixes the score bed under the picture, truncated to the video length and
        faded out at the end.
        """
        if not audio_path.exists():
            raise FileNotFoundError(f"Audio file not found: {audio_path}")

        meta = self.probe_video(video_path)
        duration = meta["duration_seconds"]

        output_path.parent.mkdir(parents=True, exist_ok=True)
        fade_start = max(0.0, duration - 2.0)
        audio_filter = f"volume={volume},afade=t=out:st={fade_start:.2f}:d=2.0"

        cmd = [
            self._ffmpeg_path,
            "-y",
            "-i", str(video_path),
            "-i", str(audio_path),
            "-filter_complex", f"[1:a]{audio_filter}[aout]",
            "-map", "0:v",
            "-map", "[aout]",
            "-c:v", "copy",
            "-c:a", "aac",
            "-b:a", "192k",
            "-t", f"{duration:.3f}",
            "-movflags", "+faststart",
            str(output_path),
        ]

        logger.info(f"Mixing score bed into walkthrough at volume {volume}")
        self._run(cmd, "mixing the background score")
        return output_path

    # ── misc helpers used by the report ───────────────────────────────────
    def extract_frame(self, video_path: Path, at_seconds: float, output_path: Path) -> Path:
        """Writes a single frame to disk — used by the review page generator."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        cmd = [
            self._ffmpeg_path,
            "-y",
            "-ss", f"{max(0.0, at_seconds):.3f}",
            "-i", str(video_path),
            "-frames:v", "1",
            str(output_path),
        ]
        self._run(cmd, f"extracting a frame from {video_path.name}")
        return output_path


ffmpeg_engine = FFmpegEngine()
